
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { DiagnosisData } from '@/pages/Index';
import { save, share } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';

interface DiagnosisResultProps {
  data: DiagnosisData;
}

export const DiagnosisResult = ({ data }: DiagnosisResultProps) => {
  const { toast } = useToast();

  const handleSave = () => {
    // In a real app, this would save to local storage or a database
    const textContent = `
Plant Diagnosis Report
======================

✅ Diagnosis: ${data.diagnosis}

🔧 Cause: ${data.cause}

💊 Solution: ${data.solution}

🌱 Prevention Tips: ${data.prevention}

Generated by PlantDoctor AI
    `.trim();

    const blob = new Blob([textContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'plant-diagnosis.txt';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast({
      title: "Report saved!",
      description: "Your diagnosis report has been downloaded",
    });
  };

  const handleShare = async () => {
    const shareText = `Plant Diagnosis: ${data.diagnosis}\n\nSolution: ${data.solution}\n\nGenerated by PlantDoctor AI`;
    
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'Plant Diagnosis Report',
          text: shareText,
        });
      } catch (err) {
        console.log('Error sharing:', err);
        fallbackShare(shareText);
      }
    } else {
      fallbackShare(shareText);
    }
  };

  const fallbackShare = (text: string) => {
    navigator.clipboard.writeText(text);
    toast({
      title: "Copied to clipboard!",
      description: "You can now paste and share the diagnosis",
    });
  };

  return (
    <Card className="p-6 bg-white shadow-lg">
      <div className="flex items-center justify-between mb-6">
        <h2 className="text-xl font-semibold text-green-800">
          🔍 Diagnosis Results
        </h2>
        <div className="flex space-x-2">
          <Button 
            variant="outline" 
            size="sm"
            onClick={handleSave}
            className="border-green-300 text-green-600 hover:bg-green-50"
          >
            <save size={16} className="mr-1" />
            Save
          </Button>
          <Button 
            variant="outline" 
            size="sm"
            onClick={handleShare}
            className="border-green-300 text-green-600 hover:bg-green-50"
          >
            <share size={16} className="mr-1" />
            Share
          </Button>
        </div>
      </div>

      <div className="space-y-6">
        <div className="border-l-4 border-red-400 pl-4">
          <h3 className="font-semibold text-red-700 mb-2 flex items-center">
            ✅ Diagnosis
          </h3>
          <p className="text-gray-700">{data.diagnosis}</p>
        </div>

        <div className="border-l-4 border-orange-400 pl-4">
          <h3 className="font-semibold text-orange-700 mb-2 flex items-center">
            🔧 Cause
          </h3>
          <p className="text-gray-700">{data.cause}</p>
        </div>

        <div className="border-l-4 border-blue-400 pl-4">
          <h3 className="font-semibold text-blue-700 mb-2 flex items-center">
            💊 Solution
          </h3>
          <p className="text-gray-700">{data.solution}</p>
        </div>

        <div className="border-l-4 border-green-400 pl-4">
          <h3 className="font-semibold text-green-700 mb-2 flex items-center">
            🌱 Prevention Tips
          </h3>
          <p className="text-gray-700">{data.prevention}</p>
        </div>
      </div>

      <div className="mt-6 p-4 bg-green-50 rounded-lg">
        <p className="text-sm text-green-700">
          <strong>Note:</strong> This diagnosis is AI-generated. For severe cases or if symptoms persist, 
          please consult with a local agricultural expert or extension officer.
        </p>
      </div>
    </Card>
  );
};
